"""
Django settings for mbc_website project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path, PurePath
from import_export.formats.base_formats import CSV

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_URL = '/media/'
MEDIA_ROOT = PurePath(BASE_DIR, 'media')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5png92==hs!1%dndh4$=%+$whe_-4fll+6c(osy===3!1dg+0e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.5.138', 'mbc_website.24livehost.com', '111.93.53.163', '*']

# Application definition

INSTALLED_APPS = [
    'djboomin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party modules
    'solo',
    'django_recaptcha',
    'easy_thumbnails',
    'file_manager',
    'colorfield',
    'import_export',
    'phonenumber_field',
    'django_select2',

    # Modules
    'page',
    'settings',
    'enquiry',
    'faq',
    'blog',
    'location',
    'rules',
    'members',
    'tournament'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mbc_website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'settings.context_processors.settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'mbc_website.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mbc_website_db',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '3307',
        'OPTIONS': {
            # "init_command": "SET GLOBAL max_connections = 100000", #<-- The fix
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/


STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static"
]

EMAIL_HOST = 'mail.24livehost.com'
EMAIL_HOST_USER = 'ds25@24livehost.com'
EMAIL_HOST_PASSWORD = 'Dsmtp@909#'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

TO_EMAIL = 'harish.kumar@dotsquares.com'
FROM_EMAIL = 'harish.kumar@dotsquares.com'

RECAPTCHA_PUBLIC_KEY = '6Lfl6RcaAAAAAGrG946PcoD7YigQlUjgcK9cscRO'
RECAPTCHA_PRIVATE_KEY = '6Lfl6RcaAAAAAG9YgPWcr9nRDlrZx-7KAiacU8W7'

RECAPTCHA_PROXY = {'http': 'http://127.0.0.1:8000', 'https': 'https://127.0.0.1:8000'}

IMPORT_FORMATS = [CSV]
# single export options
EXPORT_FORMATS = [CSV]


# CACHES = {
#     # … default cache config and others
#     "select2": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": "redis://127.0.0.1:6379/2",
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#         }
#     }
# }

# Tell select2 which cache configuration to use:
# SELECT2_CACHE_BACKEND = "select2"
SELECT2_USE_BUNDLED_JQUERY  = True
SELECT2_USE_BUNDLED_SELECT2   = True