# Generated by Django 5.1.6 on 2025-03-29 03:50

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tournament Name')),
                ('total_allowed_registration', models.PositiveSmallIntegerField(verbose_name='Total Allowed Registration')),
                ('is_current_active', models.BooleanField(default=False, verbose_name='Is this Current Tournament')),
                ('status', models.PositiveIntegerField(choices=[('', 'Status'), (0, 'In Process'), (1, 'Active'), (2, 'Completed')], verbose_name='Select Status')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('fee', models.PositiveSmallIntegerField(verbose_name='Fees')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Your Name')),
                ('certificate_name', models.CharField(blank=True, max_length=255, verbose_name='Your Name on Certificate? Please leave empty if Same as above')),
                ('partner_name', models.CharField(max_length=255, verbose_name='Your partner name? If not confirmed please add NA')),
                ('certificate_partner_name', models.CharField(blank=True, max_length=255, verbose_name='Your partner name on Certificate? If not confirmed please add NA or leave empty if Same as above')),
                ('team_name', models.CharField(blank=True, max_length=255, verbose_name='Team Name? If not sure please add NA')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='CA', verbose_name='Your mobile number (this would be used for WA messaging the tournament details)')),
                ('email', models.CharField(blank=True, max_length=255)),
                ('comments', models.CharField(blank=True, max_length=500, verbose_name='Any questions/ comments - please add.')),
                ('unisex_cap_order', models.BooleanField(default=False, verbose_name='Unisex cap - white color/ black print')),
                ('is_subscribe_for_email', models.BooleanField(default=True, verbose_name='Subscribes to Updates')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_updated_by', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
                ('category', models.ManyToManyField(to='tournament.tournamentcategory')),
            ],
        ),
    ]
