# Generated by Django 5.1.6 on 2025-03-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='title',
            field=models.CharField(default='hello', max_length=100, unique=True, verbose_name='Tournament Title'),
            preserve_default=False,
        ),
    ]
