# Generated by Django 5.1.6 on 2025-04-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='certificate_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Your Name on certificate? Please leave empty if same as above'),
        ),
        migrations.AlterField(
            model_name='player',
            name='certificate_partner_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Your partner name on certificate? If not confirmed please add NA or leave empty if same as above'),
        ),
        migrations.AlterField(
            model_name='player',
            name='facility_request',
            field=models.BooleanField(default=False, verbose_name='Facility Request Acknowledged (required)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='terms_confirmed',
            field=models.BooleanField(default=False, verbose_name='Terms & Conditions Acknowledged (required)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='tournament_rules',
            field=models.BooleanField(default=False, verbose_name='Tournament Rules Acknowledged (required) '),
        ),
    ]
