# Generated by Django 5.2.12 on 2026-04-03 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_alter_player_certificate_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentWinnerPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.CharField(blank=True, help_text='Short summary shown on the listing page', max_length=500)),
                ('content', models.TextField(help_text='Full winner details – supports rich text')),
                ('banner', models.ImageField(blank=True, upload_to='winners/banners')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published?')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='winner_page', to='tournament.tournament')),
            ],
            options={
                'verbose_name': 'Tournament Winner Page',
                'verbose_name_plural': 'Tournament Winner Pages',
                'ordering': ['-tournament__tournament_date_time'],
            },
        ),
    ]
