# Generated by Django 5.2.12 on 2026-05-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tournamentwinnerpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='show_on_teams_page',
            field=models.BooleanField(default=False, verbose_name='Show on Teams Page?'),
        ),
    ]
