# Generated by Django 5.1.6 on 2025-03-29 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tournamentcategory_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='last_registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registration Last Date Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tournament Date Time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournament',
            name='is_current_active',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='tournamentcategory',
            name='fee',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Fees'),
        ),
    ]
