# Generated by Django 5.1.6 on 2025-03-29 21:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_tournament_last_registration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='terms_confirmed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='address',
            field=models.CharField(default=1, max_length=500, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='venue',
            field=models.CharField(default='', max_length=255, verbose_name='Venue'),
            preserve_default=False,
        ),
    ]
