# Generated by Django 5.2.12 on 2026-05-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_add_show_on_teams_page_to_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='show_on_teams_dropdown',
            field=models.BooleanField(default=False, verbose_name='Show in Teams Dropdown?'),
        ),
    ]
