# Generated by Django 5.1.6 on 2025-03-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_player_terms_confirmed_tournament_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='term_condition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
