# Generated by Django 5.1.6 on 2025-03-30 22:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_tournament_term_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_subscribe_for_email',
        ),
        migrations.AddField(
            model_name='player',
            name='facility_request',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='opt_in',
            field=models.BooleanField(default=True, verbose_name="Opt-In: Consent required, If Milton Masters can collect and store your team's tournament performance, for reporting annual progression."),
        ),
        migrations.AddField(
            model_name='player',
            name='tournament_rules',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='facility_request',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='opt_in',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='show_on_home',
            field=models.BooleanField(default=False, verbose_name='Show On Home Page?'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_rules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentcategory',
            name='code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournamentcategory',
            name='end_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournamentcategory',
            name='start_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='comments',
            field=models.CharField(blank=True, max_length=500, verbose_name='Any questions/comments - please add.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='unisex_cap_order',
            field=models.BooleanField(default=False, verbose_name='Unisex cap - white color/black print'),
        ),
    ]
