# Generated by Django 5.1.6 on 2025-04-01 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_remove_player_is_subscribe_for_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='category',
        ),
        migrations.AlterField(
            model_name='player',
            name='certificate_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Your Name on Certificate? Please leave empty if same as above'),
        ),
        migrations.AlterField(
            model_name='player',
            name='certificate_partner_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Your partner name on Certificate? If not confirmed please add NA or leave empty if same as above'),
        ),
        migrations.AlterField(
            model_name='player',
            name='facility_request',
            field=models.BooleanField(default=False, verbose_name='Facility Request Acknowledged'),
        ),
        migrations.AlterField(
            model_name='player',
            name='opt_in',
            field=models.BooleanField(default=False, verbose_name="Opt-In: Consent required, If Milton Masters can collect and store your team's tournament performance, for reporting annual progression."),
        ),
        migrations.AlterField(
            model_name='player',
            name='terms_confirmed',
            field=models.BooleanField(default=False, verbose_name='Terms & Conditions Acknowledged'),
        ),
        migrations.AlterField(
            model_name='player',
            name='tournament_rules',
            field=models.BooleanField(default=False, verbose_name='Tournament Rules Acknowledged'),
        ),
        migrations.AlterField(
            model_name='player',
            name='unisex_cap_order',
            field=models.BooleanField(default=False, verbose_name='Unisex cap - White Color/Black print $5/each'),
        ),
        migrations.AlterField(
            model_name='tournamentcategory',
            name='end_date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tournamentcategory',
            name='start_date_time',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='player',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tournament.tournamentcategory'),
            preserve_default=False,
        ),
    ]
