# Generated by Django 5.1.6 on 2025-04-02 17:16

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_remove_player_category_alter_player_certificate_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='category',
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='CA', verbose_name='Your mobile number (this would be used for WA messaging the tournament details)'),
        ),
        migrations.AddField(
            model_name='player',
            name='category',
            field=models.ManyToManyField(to='tournament.tournamentcategory'),
        ),
    ]
