# Generated by Django 5.1.6 on 2025-04-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_remove_player_category_alter_player_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
        migrations.AddField(
            model_name='tournamentcategory',
            name='total_allowed_registration',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Total Allowed Registration'),
            preserve_default=False,
        ),
    ]
