# Generated by Django 5.2.12 on 2026-05-16 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Fixture Category',
                'verbose_name_plural': 'Fixture Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FixtureCourt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='fixtures.fixturecategory')),
            ],
            options={
                'verbose_name': 'Fixture Court',
                'verbose_name_plural': 'Fixture Courts',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FixtureMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.PositiveSmallIntegerField()),
                ('team1', models.CharField(max_length=200)),
                ('team2', models.CharField(max_length=200)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='fixtures.fixturecourt')),
            ],
            options={
                'ordering': ['match_number'],
            },
        ),
        migrations.CreateModel(
            name='FixtureTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.CharField(max_length=20)),
                ('pair_name', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='fixtures.fixturecourt')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
