# Generated by Django 5.2.12 on 2026-05-16 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0002_fixturecategory_fixturecourt_fixturematch_and_more'),
        ('tournament', '0005_add_show_on_teams_dropdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixturecategory',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixture_categories', to='tournament.tournament'),
        ),
    ]
