# Generated by Django 5.1.6 on 2025-02-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=70)),
                ('meta_description', models.CharField(max_length=160)),
                ('page_banner', models.ImageField(blank=True, upload_to='banner')),
                ('section_1_title', models.CharField(max_length=255)),
                ('section_1_description', models.TextField()),
                ('section_1_image', models.ImageField(blank=True, upload_to='aboutus')),
                ('section_2_image', models.ImageField(blank=True, upload_to='aboutus')),
                ('section_2_content_1', models.TextField()),
                ('section_2_content_2', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=70)),
                ('meta_description', models.CharField(max_length=160)),
                ('page_banner', models.ImageField(blank=True, upload_to='banner')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Blog Page',
                'verbose_name_plural': 'Blog Page',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=70)),
                ('meta_description', models.CharField(max_length=160)),
                ('page_banner', models.ImageField(blank=True, upload_to='banner')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Contact Page',
                'verbose_name_plural': 'Contact Page',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=70)),
                ('meta_description', models.CharField(max_length=160)),
                ('page_banner', models.ImageField(blank=True, upload_to='banner')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ Page',
                'verbose_name_plural': 'FAQ Page',
            },
        ),
        migrations.CreateModel(
            name='GenericPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=70)),
                ('meta_description', models.CharField(max_length=160)),
                ('page_banner', models.ImageField(blank=True, upload_to='banner')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=70)),
                ('meta_description', models.CharField(max_length=160)),
                ('page_banner', models.ImageField(blank=True, upload_to='banner')),
                ('section_1_title', models.CharField(max_length=255)),
                ('section_1_description', models.TextField()),
                ('section_1_image', models.ImageField(blank=True, upload_to='home')),
                ('section_1_more_button_link', models.CharField(blank=True, max_length=255)),
                ('section_2_part_1_image', models.ImageField(blank=True, upload_to='home')),
                ('section_2_part_1_title', models.CharField(max_length=255)),
                ('section_2_part_1_description', models.TextField(blank=True)),
                ('section_2_part_1_more_button_link', models.CharField(blank=True, max_length=255)),
                ('section_2_part_2_image', models.ImageField(blank=True, upload_to='home')),
                ('section_2_part_2_title', models.CharField(max_length=255)),
                ('section_2_part_2_description', models.TextField(blank=True)),
                ('section_2_part_2_more_button_link', models.CharField(blank=True, max_length=255)),
                ('section_2_part_3_image', models.ImageField(blank=True, upload_to='home')),
                ('section_2_part_3_title', models.CharField(max_length=255)),
                ('section_2_part_3_description', models.TextField(blank=True)),
                ('section_2_part_3_more_button_link', models.CharField(blank=True, max_length=255)),
                ('section_2_part_4_image', models.ImageField(blank=True, upload_to='home')),
                ('section_2_part_4_title', models.CharField(max_length=255)),
                ('section_2_part_4_description', models.TextField(blank=True)),
                ('section_2_part_4_more_button_link', models.CharField(blank=True, max_length=255)),
                ('section_3_title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Page',
            },
        ),
        migrations.CreateModel(
            name='HomePageCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=70)),
                ('meta_description', models.CharField(max_length=160)),
                ('page_banner', models.ImageField(blank=True, upload_to='banner')),
                ('section_2_image', models.ImageField(blank=True, upload_to='aboutus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=70)),
                ('meta_description', models.CharField(max_length=160)),
                ('page_banner', models.ImageField(blank=True, upload_to='banner')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_1', models.ImageField(blank=True, upload_to='membership')),
                ('image_2', models.ImageField(blank=True, upload_to='membership')),
            ],
            options={
                'verbose_name': 'Membership Page',
                'verbose_name_plural': 'Membership Page',
            },
        ),
    ]
