# Generated by Django 5.1.6 on 2025-02-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='section_1_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='section_1_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='home',
            name='section_1_image',
        ),
        migrations.RemoveField(
            model_name='home',
            name='section_1_more_button_link',
        ),
        migrations.RemoveField(
            model_name='home',
            name='section_2_part_1_description',
        ),
        migrations.RemoveField(
            model_name='home',
            name='section_2_part_1_image',
        ),
        migrations.RemoveField(
            model_name='home',
            name='section_2_part_1_more_button_link',
        ),
        migrations.RemoveField(
            model_name='home',
            name='section_2_part_1_title',
        ),
        migrations.RemoveField(
            model_name='home',
            name='section_2_part_2_description',
        ),
        migrations.RemoveField(
            model_name='home',
            name='section_2_part_2_image',
        ),
        migrations.RemoveField(
            model_name='home',
            name='section_2_part_2_more_button_link',
        ),
        migrations.RemoveField(
            model_name='home',
            name='section_2_part_2_title',
        ),
        migrations.RemoveField(
            model_name='home',
            name='section_2_part_3_description',
        ),
        migrations.RemoveField(
            model_name='home',
            name='section_2_part_3_image',
        ),
        migrations.RemoveField(
            model_name='home',
            name='section_2_part_3_more_button_link',
        ),
        migrations.RemoveField(
            model_name='home',
            name='section_2_part_3_title',
        ),
        migrations.RemoveField(
            model_name='home',
            name='section_2_part_4_description',
        ),
        migrations.RemoveField(
            model_name='home',
            name='section_2_part_4_image',
        ),
        migrations.RemoveField(
            model_name='home',
            name='section_2_part_4_more_button_link',
        ),
        migrations.RemoveField(
            model_name='home',
            name='section_2_part_4_title',
        ),
        migrations.RemoveField(
            model_name='home',
            name='section_3_title',
        ),
        migrations.AddField(
            model_name='home',
            name='image',
            field=models.ImageField(blank=True, upload_to='pages'),
        ),
    ]
