# Generated by Django 5.1.6 on 2025-02-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_rename_section_1_description_home_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='section_1_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='section_1_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='section_1_image',
        ),
        migrations.RemoveField(
            model_name='about',
            name='section_2_content_1',
        ),
        migrations.RemoveField(
            model_name='about',
            name='section_2_content_2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='section_2_image',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='image_2',
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, upload_to='pages'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, upload_to='pages'),
        ),
        migrations.AddField(
            model_name='faq',
            name='image',
            field=models.ImageField(blank=True, upload_to='pages'),
        ),
        migrations.AddField(
            model_name='genericpage',
            name='description',
            field=models.TextField(default='test data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genericpage',
            name='image',
            field=models.ImageField(blank=True, upload_to='pages'),
        ),
        migrations.AddField(
            model_name='membership',
            name='image',
            field=models.ImageField(blank=True, upload_to='pages'),
        ),
    ]
