# Generated by Django 5.1.6 on 2025-02-18 05:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_rename_section_1_description_about_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecarousel',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='homepagecarousel',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='homepagecarousel',
            name='page_banner',
        ),
        migrations.RemoveField(
            model_name='homepagecarousel',
            name='section_2_image',
        ),
        migrations.AddField(
            model_name='homepagecarousel',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepagecarousel',
            name='image',
            field=models.ImageField(default=1, upload_to='homepage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepagecarousel',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecarousel',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
