# Generated by Django 5.1.6 on 2025-02-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_remove_homepagecarousel_meta_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='about',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='page_banner',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='page_banner',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='page_banner',
        ),
        migrations.RemoveField(
            model_name='genericpage',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='genericpage',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='genericpage',
            name='page_banner',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='page_banner',
        ),
    ]
