# Generated by Django 5.1.6 on 2025-03-30 04:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_remove_about_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecarousel',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
