# Generated by Django 5.1.6 on 2025-02-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('surname', models.CharField(max_length=100, null=True)),
                ('company', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=100)),
                ('enquirer_type', models.PositiveIntegerField(choices=[('', 'Enquiry Type'), (1, 'New Registration'), (2, 'Others')], verbose_name='Are you an')),
                ('referrer', models.PositiveIntegerField(choices=[('', 'How Did You Hear About Milton Badminton Club?'), (1, 'Social Media'), (2, 'Website'), (3, 'Search Engine'), (4, 'Friend/Family or collegue'), (5, 'Other')], verbose_name='How did you hear about skignz?')),
                ('sector', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(editable=False, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
            },
        ),
        migrations.CreateModel(
            name='MagicBlueCircleEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('interested_in_magic', models.BooleanField()),
                ('interested_in_skignz', models.BooleanField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(editable=False, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Magic Blue Circle Enquiries',
            },
        ),
    ]
