# Generated by Django 5.1.6 on 2025-04-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='company',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='position',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='sector',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='referrer',
            field=models.PositiveIntegerField(choices=[('', 'How Did You Hear About Milton Masters Badminton?'), (1, 'Social Media'), (2, 'Website'), (3, 'Search Engine'), (4, 'Friend/Family'), (5, 'Other')], verbose_name='How did you hear about Milton Masters Badminton?'),
        ),
    ]
