# Generated by Django 5.1.6 on 2025-02-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magicbluecircleenquiry',
            old_name='interested_in_skignz',
            new_name='interested_in_mbc',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='referrer',
            field=models.PositiveIntegerField(choices=[('', 'How Did You Hear About Milton Badminton Club?'), (1, 'Social Media'), (2, 'Website'), (3, 'Search Engine'), (4, 'Friend/Family or collegue'), (5, 'Other')], verbose_name='How did you hear about Milton Badminton Club?'),
        ),
    ]
