# Generated by Django 5.1.6 on 2025-02-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(max_length=200, upload_to='clients')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_link', models.CharField(blank=True, max_length=200)),
                ('twitter_link', models.CharField(blank=True, max_length=200)),
                ('linkedin_link', models.CharField(blank=True, max_length=200)),
                ('instagram_link', models.CharField(blank=True, max_length=200)),
                ('youtube_link', models.CharField(blank=True, max_length=200)),
                ('apple_link', models.CharField(blank=True, max_length=200)),
                ('android_link', models.CharField(blank=True, max_length=200)),
                ('accounts_link', models.CharField(blank=True, max_length=200)),
                ('enquiries_email', models.CharField(max_length=200)),
                ('office_1_name', models.CharField(blank=True, max_length=255)),
                ('office_1_address', models.TextField(blank=True)),
                ('office_1_phone', models.CharField(blank=True, max_length=255)),
                ('office_1_email', models.CharField(blank=True, max_length=255)),
                ('office_2_name', models.CharField(blank=True, max_length=255)),
                ('office_2_address', models.TextField(blank=True)),
                ('office_2_phone', models.CharField(blank=True, max_length=255)),
                ('office_2_email', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Website Settings',
                'verbose_name_plural': 'Website Settings',
            },
        ),
    ]
