# Generated by Django 5.1.6 on 2025-04-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='pages')),
            ],
            options={
                'verbose_name': 'Rules',
                'verbose_name_plural': 'Rules',
            },
        ),
    ]
