# Generated by Django 5.1.6 on 2025-02-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rules',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='page_banner',
        ),
    ]
