# Generated by Django 5.1.6 on 2025-04-07 15:17

import colorfield.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('name_on_tag', models.CharField(max_length=255, unique=True)),
                ('color', colorfield.fields.ColorField(choices=[('', 'Select Color'), ('#00FF00', 'Green'), ('#0000FF', 'Blue'), ('#FF0000', 'Red'), ('#FFFF00', 'Yellow')], default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('level', models.PositiveSmallIntegerField(choices=[('', 'Select Level'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Upper Intermediate'), (4, 'Advanced'), (5, 'Competent')])),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_subscribe_for_email', models.BooleanField(default=True, verbose_name='Subscribes to Updates')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Season Name')),
                ('is_current_active', models.BooleanField(default=False, verbose_name='Is this Current Season')),
                ('status', models.PositiveIntegerField(choices=[('', 'Status'), (1, 'Active'), (2, 'Completed')], verbose_name='Select Status')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonMemberMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_created_by', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.season')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('season', 'member')},
            },
        ),
    ]
